"""empty message

Revision ID: 36800b60f3a6
Revises: 
Create Date: 2020-04-23 20:40:03.641133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36800b60f3a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
